[feat] 장소검색 api 생성
TeamPINGLE/PINGLE-SERVER pull request #13
Opened 2024-01-06 07:30 UTC by Parkjyun

## Related Issue 📌
close #11 

## Description ✔️
- 장소 검색 api입니다.

## To Reviewers
- 현재 postman을 통해 네이버 검색 api를 직접 호출 해도 요쳥을 2번 보내야 정상적인 응답이 오는 것을 확인했습니다. 이를 해결하거나 카카오 api로 대체해야 할 것 같습니다.

2024-01-06 20:44 UTC, tkdwns414 requested changes
확인 부탁드립니다. 언급하신 요청 두 번 관련 찾으신 것 대단합니당

2024-01-06 20:44 UTC, tkdwns414 commented on src/main/java/org/pingle/pingleserver/dto/type/ErrorMessage.java
> +    NAVER_SERVER_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "네이버 서버 오류입니다.");
한가지 팁 드리면 Internal Server Error를 맨 아래로 두고 추가하면 좋을 것 같습니다!
그 아래로 추가를 하면 매번 ; 지우고 , 달고 해야하더라고요.

2024-01-06 20:44 UTC, tkdwns414 commented on src/main/java/org/pingle/pingleserver/dto/reponse/LocationResponse.java
> +}
나중에 기획 추가된 것처럼 roadAddress 넣어주세요!

2024-01-06 20:44 UTC, tkdwns414 commented on src/main/java/org/pingle/pingleserver/utils/naversearchutil/NaverUtil.java
> +    public NaverLocationResponse locationSearch(NaverLocationRequest request) {
해당 메소드는 util 안에서만 쓰일 것 같으므로 private으로 바꿔도 될 것 같습니다

2024-01-06 20:44 UTC, tkdwns414 commented on src/main/java/org/pingle/pingleserver/dto/request/NaverLocationRequest.java
> +}
dto는 record로 만들기로 했었던 것 같은데 혹시 record가 아니고 class로 하신 이유가 따로 있을까요?

2024-01-06 20:44 UTC, tkdwns414 commented on src/main/java/org/pingle/pingleserver/exception/GlobalExceptionHandler.java
> +//    }
해당 부분은 언급하신 API 요청을 두 번 날려야 성공한다고 판단하셨을 때 해놓으신 것 같은데 지금 보니 아예 지우거나 살린 후 다른 핸들러 참고해서 정상 작동하게 만드셔도 될 것 같습니다.

2024-01-07 10:19 UTC, Parkjyun commented on src/main/java/org/pingle/pingleserver/dto/request/NaverLocationRequest.java
> +}
record에 인스턴스 메서드를 추가하지 못한다고 알고 있었는데 자바17 부터 지원을 하네요. record로 바꿨습니다~

2024-01-07 10:20 UTC, Parkjyun commented on src/main/java/org/pingle/pingleserver/utils/naversearchutil/NaverUtil.java
> +    public NaverLocationResponse locationSearch(NaverLocationRequest request) {
수정했습니당

2024-01-07 10:20 UTC, Parkjyun commented on src/main/java/org/pingle/pingleserver/dto/reponse/LocationResponse.java
> +}
추가했습니다

2024-01-07 10:21 UTC, Parkjyun commented on src/main/java/org/pingle/pingleserver/exception/GlobalExceptionHandler.java
> +//    }
삭제했습니당

2024-01-07 10:24 UTC, tkdwns414 approved these changes
LGTM

2024-01-07 10:26 UTC, merged