[feat] 번개 생성 api
TeamPINGLE/PINGLE-SERVER pull request #25
Opened 2024-01-07 14:57 UTC by Parkjyun

## Related Issue 📌
close #14 

## Description ✔️
- 번개생성하는 api입니다.

## To Reviewers
- @GUserId를 통해 user의 group 가입 여부를 검증합니다.
- request의 x,y 좌표에 핀이 없다면 새로 생성한 후 번개를 생성합니다.

2024-01-07 16:29 UTC, tkdwns414 requested changes
리뷰 확인 부탁드립니다

2024-01-07 16:29 UTC, tkdwns414 commented on src/main/java/org/pingle/pingleserver/dto/request/MeetingRequest.java
> +                             Integer maxParticipants,
생각해보니까 min도 걸어주면 좋을 것 같은데 어떻게 생각하시나요?

2024-01-07 16:29 UTC, tkdwns414 commented on src/main/java/org/pingle/pingleserver/dto/type/ErrorMessage.java
> +    NO_SUCH_MEETING(HttpStatus.BAD_REQUEST, "해당하는 미팅이 없습니다." ),
해당 오류들은 404로 표시하는 것이 맞는 것 같습니다. "해당하는 ~가 없습니다"는 `NOT_FOUND_RESOURCE(HttpStatus.NOT_FOUND, "해당 리소스가 존재하지 않습니다.")`로 통일하기로 했으므로 수정 부탁드립니다.

2024-01-07 16:29 UTC, tkdwns414 commented on src/main/java/org/pingle/pingleserver/dto/type/ErrorMessage.java
> +    RESOURCE_NOT_FOUND(HttpStatus.NOT_FOUND, "리소스가 없습니다"),
NOT_FOUND_RESOURCE(HttpStatus.NOT_FOUND, "해당 리소스가 존재하지 않습니다.") 로 하고 겹치는 것 지우기로 했던 것 같은데 얘기한 것과 달라진 것 같습니다. 수정 부탁드립니다.

2024-01-07 16:29 UTC, tkdwns414 commented on src/main/java/org/pingle/pingleserver/interceptor/pre/GUserIdArgumentResolver.java
> +        }
Principal이 들어있지 않다는 것은 Filter가 동작했는데 유저 정보가 담기지 않았다는 뜻이니까 NO_SUCH_USER(그런 유저가 없다) 보다는 INVALID_JWT_TOKEN 혹은 JWT_TOKEN_IS_EMPTY가 더 맞는 것 같아요. 
Filter에서 오류가 터지지 않았다는 것은 JWT는 유효하다는 뜻인 것 같은데 해당 부분이랑 UserIdArgumentResolver에서 같은 부분도 JWT_TOKEN_IS_EMPTY로 고쳐주실 수 있으실까요?

2024-01-07 16:29 UTC, tkdwns414 commented on src/main/java/org/pingle/pingleserver/interceptor/pre/GUserIdArgumentResolver.java
> +        Long groupId = Long.valueOf(webRequest.getHeader("Group-Id"));
Group-Id 헤더가 비어있다는 것은 ErrorMessage 중 MISSING_REQUIRED_HEADER에 더 적합한 에러 같습니다.

2024-01-09 06:13 UTC, Parkjyun commented on src/main/java/org/pingle/pingleserver/dto/type/ErrorMessage.java
> +    NO_SUCH_MEETING(HttpStatus.BAD_REQUEST, "해당하는 미팅이 없습니다." ),
다른 곳에서 쓰는 곳이 있어서 머지하고 수정하겠습니다

2024-01-09 06:13 UTC, Parkjyun commented on src/main/java/org/pingle/pingleserver/dto/request/MeetingRequest.java
> +                             Integer maxParticipants,
반영했습니다

2024-01-09 06:14 UTC, Parkjyun commented on src/main/java/org/pingle/pingleserver/dto/type/ErrorMessage.java
> +    RESOURCE_NOT_FOUND(HttpStatus.NOT_FOUND, "리소스가 없습니다"),
따로 이슈 파서 작업하겠습니다

2024-01-09 06:18 UTC, Parkjyun commented on src/main/java/org/pingle/pingleserver/interceptor/pre/GUserIdArgumentResolver.java
> +        }
위에 언급한 이슈랑 같이 작업하겠습니다.

2024-01-09 06:18 UTC, Parkjyun commented on src/main/java/org/pingle/pingleserver/interceptor/pre/GUserIdArgumentResolver.java
> +        Long groupId = Long.valueOf(webRequest.getHeader("Group-Id"));
위 이슈랑 같이 작업하겠습니다.

2024-01-09 06:55 UTC, merged